### ISSUE TITLE
hekp file hex lost most alarm 

### ISSUE THREAD

**Issue by jonathan2018** [ladipro/pic_projects#2]
can you post file hex for project lost mosrt alarm with 12f629 ?

thanks

**Comment by ladipro** [comment]
Sure, try this:
[PIC12F629_LostModelFinder.production.zip](https://github.com/ladipro/pic_projects/files/2217073/PIC12F629_LostModelFinder.production.zip)

**Comment by jonathan2018** [comment]
@ladipro 

Thank for file Hex , i tested  and it work wrong , can not set up value Channel to ALARM . when lost signal , it also do not work ,Sound not good ,small volume . 
range  PWM channel from 1000-2000 and i need > 1500  alarm , lost signal - alarm 

can you fix this problem ?
